@echo off
REM =====================================================
REM Processar empresas prioritárias que tiveram problemas
REM =====================================================

echo ==========================================
echo PROCESSAMENTO DE EMPRESAS PRIORITARIAS
echo ==========================================
echo.
echo Este script processa apenas as 190 empresas
echo que tiveram problemas devido ao travamento.
echo.

REM Ativar ambiente virtual
echo Ativando ambiente virtual...
call .venv\Scripts\activate

REM Criar arquivo Python temporário com a lista de empresas
echo Criando lista de empresas prioritarias...
python -c "
empresas_prioritarias = [
    'VIAMEX_LOGISTICA_E_TRANSPORTES_LTDA',
    'COOPERATIVA_DE_TRANSPORTES_DE_CARGAS_QUIMICAS_E_CORROSIVAS_DE_MAUA',
    'TC_SERVICOS_DE_TRANSPORTES_LTDA',
    'E_LOG_TRANSPORTES_LTDA',
    'TRANSPORTADORA_DIRECIONAL_LTDA',
    'BRASPRESS_TRANSPORTES_URGENTES_LTDA',
    'RÁPIDO_900_TRANSPORTES_LTDA',
    'JS_NASCIMENTO_TRANSPORTES_ME',
    'TRANSPORTES_PAJUÇARA_LTDA',
    'FG_LOG_TRANSPORTES_LTDA',
    'RODOVIÁRIO_SCHIO_LTDA',
    'RODOVIÁRIO_TRÊS_MARIAS_LTDA',
    'J_PEREIRA_TRANSPORTES_LTDA',
    'E_C_PEREIRA_TRANSPORTES_ME',
    'SUPRICEL_TRANSPORTES_E_LOGÍSTICA_EIRELI',
    'R_J_S_TRANSPORTES_LTDA_ME',
    'TC_TRANSPORTES_E_LOGISTICA_LTDA',
    'D_A_TRANSPORTES_RODOVIARIOS_EIRELI',
    'TRANSPORTADORA_AMERICANA_LTDA',
    'RAPIDO_BRASILIA_TRANSPORTES_E_ENCOMENDAS_LTDA',
    'TRANSPORTE_DALCOQUIO_LTDA',
    'JBR_TRANSPORTES_RODOVIARIOS_LTDA',
    'TRANSGLOBAL_TRANSPORTES_LTDA',
    'VIA_PAJUÇARA_TRANSPORTES_LTDA',
    'VIAÇÃO_JAVAÉ_LTDA',
    'TRANSPORTES_TRANSLOVATO_LTDA',
    'TRANSLITORAL_TRANSPORTES_LTDA',
    'RODOVIÁRIO_VIVAN_S_A',
    'KIBE_TRANSPORTES_EIRELI',
    'COLATINENSE_TRANSPORTES_LTDA',
    'TRANSPORTES_LUFT_LTDA',
    'TRANSPANORAMA_TRANSPORTES_LTDA',
    'TRANSPORTADORA_RISSO_LTDA',
    'LORENLOG_TRANSPORTES_LTDA',
    'FDB_TRANSPORTES_E_LOGISTICA_LTDA',
    'RODOVIÁRIO_BONANZA_LTDA',
    'TRANSPORTES_BERTOLINI_LTDA',
    'D_F_SILVA_GOMES_TRANSPORTES_ME',
    'RAÇA_TRANSPORTES_LTDA',
    'A_J_BAPTISTA_JUNIOR_TRANSPORTES',
    'A_D_S_TRANSPORTES_EIRELI',
    'ALFA_TRANSPORTES_EIRELI',
    'TC_SUL_TRANSPORTES_LTDA',
    'WRA_TRANSPORTES_EIRELI',
    'REITER_LOG_ARMAZEM_GERAL_E_TRANSPORTES_S_A',
    'M_M_A_P_TRANSPORTES_LTDA',
    'M_C_P_AMORIM_TRANSPORTES',
    'TRANSPORTES_MANO_LTDA',
    'JADLOG_LOGISTICA_LTDA',
    'RJA_TRANSPORTES_LTDA',
    'KLL_TRANSPORTES_LTDA',
    'RTE_RODONAVES_TRANSPORTES_E_ENCOMENDAS_LTDA',
    'JS_TRANSPORTES_LTDA',
    'R_E_TRANSPORTE_LTDA',
    'TRANSPORTES_TRANSPES_LTDA',
    'J_BARBOSA_TRANSPORTES_LTDA',
    'BETA_CARGO_TRANSPORTES_EIRELI',
    'ATIVA_TRANSPORTES_E_SERVICOS_LTDA',
    'MG_TRANSPORTES_LTDA',
    'TRANSPORTADORA_DE_CARGAS_TRANSCRED_LTDA',
    'EBANI_TRANSPORTES_LTDA',
    'TRANSZAP_TRANSPORTES_LTDA',
    'NOVA_ERA_TRANSPORTES_LTDA',
    'TRANSPORTES_SÃO_MIGUEL_ARCANJO_LTDA',
    'TRANSFENIX_TRANSPORTES_LTDA',
    'FAGUNDES_TRANSPORTES_LTDA',
    'G3_TRANSPORTES_E_LOGISTICA_LTDA',
    'TRANSGLOBO_TRANSPORTES_LTDA',
    'RODOBAHIA_TRANSPORTES_LTDA',
    'L_A_R_TRANSPORTES_EIRELI',
    'RODOVIÁRIO_CENTRAL_LTDA',
    'TRANSPORTES_CAVALINHO_LTDA',
    'UNIDÃO_TRANSPORTES_E_LOGÍSTICA_LTDA',
    'TRANSOLIVEIRA_TRANSPORTES_LTDA',
    'TRANSPORTADORA_RISSO_LTDA',
    'TRANSPORTADORA_GABARDO_LTDA',
    'TRANSPORTADORA_E_LOGISTICA_LTDA',
    'TRANSCOTTA_TRANSPORTES_LTDA',
    'MILLENIUM_TRANSPORTES_LTDA',
    'VOLPI_TRANSPORTES_LTDA',
    'TRANSBASE_TRANSPORTES_LTDA',
    'FL_BRASIL_HOLDING_LOGISTICA_E_TRANSPORTE_LTDA',
    'DBS_TRANSPORTES_E_LOGISTICA_LTDA',
    'J_R_A_TRANSPORTES_E_LOGISTICA_LTDA',
    'TRANSPORTES_BERTOLINI_LTDA',
    'BRASPRESS_TRANSPORTES_URGENTES_LTDA',
    'J_BELINE_TRANSPORTES_LTDA',
    'J_D_TRANSPORTES_LTDA',
    'SR_TRANSPORTES_LTDA',
    'TRANSJORDANO_TRANSPORTES_LTDA',
    'J_E_MANFRON_TRANSPORTES_LTDA',
    'J_C_TRANSPORTES_E_MUDANCAS_LTDA',
    'DJ_TRANSPORTES_LTDA',
    'TRANSPORTES_CAVALINHO_LTDA',
    'TRANSCONSULT_TRANSPORTES_LTDA',
    'JB_TRANSPORTES_LTDA',
    'V_TRANS_TRANSPORTES_LTDA',
    'RODOVIÁRIO_DE_CARGAS_PAGANINI_LTDA',
    'LOG_TRANSPORTES_LTDA',
    'EXPRESSO_NEPOMUCENO_S_A',
    'RB_TRANSPORTES_E_CARGAS_LTDA',
    'TRANSPORTES_TRANSLOVATO_LTDA',
    'TRANSOLIVEIRA_TRANSPORTES_LTDA',
    'TRANSPORTES_PAJUÇARA_LTDA',
    'TRANSPORTADORA_PAJUÇARA_LTDA',
    'J_P_S_TRANSPORTES_LTDA',
    'TRANS_TAMBAÚ_TRANSPORTES_LTDA',
    'R_E_TRANSPORTES_LTDA',
    'TRANSLITORAL_TRANSPORTES_LTDA',
    'V_TRANS_TRANSPORTES_LTDA',
    'TRANSPORTADORA_GABARDO_LTDA',
    'RODOVIÁRIO_DE_CARGAS_PAGANINI_LTDA',
    'TRANSOLIVEIRA_TRANSPORTES_LTDA',
    'MILLENIUM_TRANSPORTES_LTDA',
    'TRANSPORTADORA_E_LOGISTICA_LTDA',
    'TRANSCOTTA_TRANSPORTES_LTDA',
    'J_D_TRANSPORTES_LTDA',
    'SR_TRANSPORTES_LTDA',
    'TRANSJORDANO_TRANSPORTES_LTDA',
    'COLATINENSE_TRANSPORTES_LTDA',
    'J_E_MANFRON_TRANSPORTES_LTDA',
    'J_C_TRANSPORTES_E_MUDANCAS_LTDA',
    'DJ_TRANSPORTES_LTDA',
    'TRANSPORTES_CAVALINHO_LTDA',
    'TRANSCONSULT_TRANSPORTES_LTDA',
    'JB_TRANSPORTES_LTDA',
    'DBS_TRANSPORTES_E_LOGISTICA_LTDA',
    'RB_TRANSPORTES_E_CARGAS_LTDA',
    'JADLOG_LOGISTICA_LTDA',
    'WRA_TRANSPORTES_EIRELI',
    'E_LOG_TRANSPORTES_LTDA',
    'MG_TRANSPORTES_LTDA',
    'TRANSPORTADORA_DE_CARGAS_TRANSCRED_LTDA',
    'J_P_S_TRANSPORTES_LTDA',
    'TRANS_TAMBAÚ_TRANSPORTES_LTDA',
    'R_E_TRANSPORTES_LTDA',
    'TRANSLITORAL_TRANSPORTES_LTDA',
    'V_TRANS_TRANSPORTES_LTDA',
    'TRANSPORTADORA_GABARDO_LTDA',
    'RODOVIÁRIO_DE_CARGAS_PAGANINI_LTDA',
    'TRANSOLIVEIRA_TRANSPORTES_LTDA',
    'MILLENIUM_TRANSPORTES_LTDA',
    'TRANSPORTADORA_E_LOGISTICA_LTDA',
    'TRANSCOTTA_TRANSPORTES_LTDA',
    'J_D_TRANSPORTES_LTDA',
    'SR_TRANSPORTES_LTDA',
    'TRANSJORDANO_TRANSPORTES_LTDA',
    'COLATINENSE_TRANSPORTES_LTDA',
    'J_E_MANFRON_TRANSPORTES_LTDA',
    'J_C_TRANSPORTES_E_MUDANCAS_LTDA',
    'DJ_TRANSPORTES_LTDA',
    'TRANSPORTES_CAVALINHO_LTDA',
    'TRANSCONSULT_TRANSPORTES_LTDA',
    'JB_TRANSPORTES_LTDA',
    'DBS_TRANSPORTES_E_LOGISTICA_LTDA',
    'RB_TRANSPORTES_E_CARGAS_LTDA',
    'TRANSPORTES_TRANSPES_LTDA',
    'J_BARBOSA_TRANSPORTES_LTDA',
    'BETA_CARGO_TRANSPORTES_EIRELI',
    'ATIVA_TRANSPORTES_E_SERVICOS_LTDA',
    'EBANI_TRANSPORTES_LTDA',
    'TRANSZAP_TRANSPORTES_LTDA',
    'NOVA_ERA_TRANSPORTES_LTDA',
    'TRANSPORTES_SÃO_MIGUEL_ARCANJO_LTDA',
    'TRANSFENIX_TRANSPORTES_LTDA',
    'FAGUNDES_TRANSPORTES_LTDA',
    'G3_TRANSPORTES_E_LOGISTICA_LTDA',
    'TRANSGLOBO_TRANSPORTES_LTDA',
    'RODOBAHIA_TRANSPORTES_LTDA',
    'L_A_R_TRANSPORTES_EIRELI',
    'RODOVIÁRIO_CENTRAL_LTDA',
    'TRANSPORTES_CAVALINHO_LTDA',
    'UNIDÃO_TRANSPORTES_E_LOGÍSTICA_LTDA',
    'VOLPI_TRANSPORTES_LTDA',
    'TRANSBASE_TRANSPORTES_LTDA',
    'FL_BRASIL_HOLDING_LOGISTICA_E_TRANSPORTE_LTDA',
    'J_R_A_TRANSPORTES_E_LOGISTICA_LTDA',
    'TRANSPORTES_BERTOLINI_LTDA',
    'BRASPRESS_TRANSPORTES_URGENTES_LTDA',
    'J_BELINE_TRANSPORTES_LTDA',
    'LOG_TRANSPORTES_LTDA',
    'EXPRESSO_NEPOMUCENO_S_A',
    'RJA_TRANSPORTES_LTDA',
    'KLL_TRANSPORTES_LTDA',
    'RTE_RODONAVES_TRANSPORTES_E_ENCOMENDAS_LTDA',
    'JS_TRANSPORTES_LTDA'
]

# Salvar lista em arquivo temporário
with open('empresas_prioritarias.txt', 'w', encoding='utf-8') as f:
    for empresa in empresas_prioritarias:
        f.write(empresa + '\n')

print(f'Total de empresas prioritárias: {len(empresas_prioritarias)}')
"

REM Executar processamento apenas das empresas prioritárias
echo.
echo Iniciando processamento das empresas prioritarias...
echo.

python app/run.py data/cadastro_empresas.xlsx --filter-file empresas_prioritarias.txt

REM Limpar arquivo temporário
del empresas_prioritarias.txt

echo.
echo ==========================================
echo PROCESSAMENTO CONCLUIDO!
echo ==========================================
echo.